### PR TITLE
Port the OCaml implementation to Rust

### PR DESCRIPTION
**Pull request by brendanzab**
As [mentioned on Twitter](https://twitter.com/brendanzab/status/1376797836168159235), I had a go at porting the OCaml code to Rust today! It's probably not fit to merge as-is, but thought you might be interested in seeing it!

Some things to note:

- I used [rust-peg](https://github.com/kevinmehall/rust-peg/) for the parser, which might go against your existing approach of having no external dependencies. It made things a bit quicker for me though!
- I also have some Cargo configuration stuff in the root of the repository - having a global workspace is nicer for development using [rust-analyzer](https://rust-analyzer.github.io/), but I can remove that if you like.
- I still need to figure out how to get a hold of an ARM assembler, but I've looked at the output and it seems to emit some reasonable-looking assembly. I might have made some transcription errors though!
- I noticed that you hadn't implemented assert statements in the OCaml parser. 😅

### CODE REVIEW

**Comment by brendanzab** [comment]
Oh, and should also be worth noting that I still need to see about running this through an ARM assembler, but I've tested and it seems to emit some reasonable-looking assembly. I might have made some transcription errors though!

I also found that you hadn't implemented 'assert_statements' in the OCaml implementation.

**Comment by keleshev** [comment]
This is really cool! I will have to take a closer look in the evening.

**Comment by keleshev** [comment]
I think this has value in being merged as-is. Let me know if I should hold it back.

Hypothetical improvements for the future:
* Non-library parser that matches the book's approach.
* One way to assert that it is correct is to make sure that the output is exactly the same as the other ports (Python and OCaml ports produce exactly the same output as the TypeScript one).

> I noticed that you hadn't implemented assert statements in the OCaml parser. 

Parsing assert is a sort of intermediary bootstrapping step in the book narrative. Later it is replaced with an actual `assert` function. (I think it is the same with main).

**Comment by brendanzab** [comment]
> Non-library parser that matches the book's approach.

Yeah, definitely think that a parser combinator approach would be better in the future to match the book. Was mainly interested in the compiler aspect which is why I jumped to that, and am now reading the relevant parts of the book (which are good!) 😅

Rust does kind of struggle a bit with returning closures from functions, so it might take a bit of care to design it in a way that is both elegant and compact and in keeping with the spirit of the book. Perhaps using a [Nom-style of approach](https://doma.dev/blog/parsing-stuff-in-rust/) where you pass the input stream manually to the combinators might work. It's been a while since I tried doing parser combinators in Rust (like, many years, haha). 

Anyway, nothing major blocking a merge if you're happy with my caveats!

**Comment by brendanzab** [comment]
Oh, this article on parser combinators in Rust looks good too: [Learning Parser Combinators With Rust](https://bodil.lol/parser-combinators/) - it uses the approach where you return unboxed closures. It seems to not be as bad I remembered!

**Comment by keleshev** [comment]
@brendanzab, thank you! This will be valuable to many readers, as many have already shown interest in a Rust port. 

If you don't mind, I will send a broadcast to the book's email list, notifying that a Rust port is available.

**Comment by brendanzab** [comment]
Feel free! :)

**Pull request merged**
